### ISSUE TITLE
confusion during rendering sequence

### ISSUE THREAD

**Issue by renaissanceee** [ZcsrenlongZ/ZoomGS#5]
what's the difference of [L230](https://github.com/ZcsrenlongZ/ZoomGS/blob/e3c6fb9bdf5776467e5f0ff37f7177df83deabcd/ZoomGS/zoomgs_render.py#L230) and [L241](https://github.com/ZcsrenlongZ/ZoomGS/blob/e3c6fb9bdf5776467e5f0ff37f7177df83deabcd/ZoomGS/zoomgs_render.py#L241)?
could be treated as overwriting?

**Comment by ZcsrenlongZ** [comment]
L230~L237 only interpolates between intrinsic parameters，which can be regared as to implement SR between x0.6 ~ x0.85; L241 ~ L247 interpolates between intrinsic and extrinsic parameters, which can be regared as to implement camera transition between x0.85 ~ x1.0.

**Comment by renaissanceee** [comment]
As my understanding, the processed cam_param has been included in the array "linear_views".
Therefore, L230~L237 has already included x0.6 ~x0.85 and x0.85 ~x1, isn't it?

Or maybe, you mean to add "linear_views = linear_views[:N_C]" before L230?

________________________________
发件人: ZcsrenLongZ ***@***.***>
发送时间: 2024年9月9日 8:51:17
收件人: ZcsrenlongZ/ZoomGS
抄送: Li, Jiameng; Author
主题: Re: [ZcsrenlongZ/ZoomGS] confusion during rendering sequence (Issue #5)


Closed #5<https://github.com/ZcsrenlongZ/ZoomGS/issues/5> as completed.

―

**Comment by ZcsrenlongZ** [comment]
Thanks for your reminder, I will check it later.

**Comment by renaissanceee** [comment]
In addition, I'm curious about the **pre-selection**.
[L261](https://github.com/ZcsrenlongZ/ZoomGS/blob/main/ZoomGS/zoomgs_render.py#L261) collects train_views, in which uw&w have attended training. But later, [L219](https://github.com/ZcsrenlongZ/ZoomGS/blob/main/ZoomGS/zoomgs_render.py#L219) select 4th and 7th train_view to generate sequence. What's the reason for the additional selection in 219?
Obviously, no novel-view is included in the continuous sequence.

**Comment by ZcsrenlongZ** [comment]
You are right.  For each scene, we collect 15 paried UW and W images (6 additional W images). 5 paired UW and W images are used to evaluate ZoomGS performance, and other images are used as train ZoomGS. After training, we can generate continuous sequences from ZoomGS to finetune FI model. Of course, we can use views of all UW and W pairs to generate such sequence. Considering that the image content from different views  in a scene is similar (more views may benefit FI models little), we just simply choose two views of UW&W pairs to generate such sequences.

**Comment by renaissanceee** [comment]
Thanks for your clear illustration, and wish you a good day.
