### ISSUE TITLE
Regarding the results of Table 2

### ISSUE THREAD

**Issue by LeiWangCV** [ZcsrenlongZ/ZoomGS#6]
Hello, I am unable to experiment with the results shown in Table 2 myself. Specifically, using the 3DGS method, the results on the 01 data are as follows:
PSNR PSNR LPIPS     PSNR PSNR LPIPS
01-wide    15.5054 0.6641 0.3481    24.4481 0.8025 0.2371
01-uw       24.633 0.8994 0.25        18.8096 0.6777 0.3672
01-all 28.2329 0.9188 0.1987   29.2199 0.8906 0.1891
01zoom   33.037     0.9514     0.16165  30.2128  0.9014    0.18743
Use 5 paired UW and W images for evaluation, and the rest for testing. But there is a big gap in 3dgs and it cannot be consistent with Table 2. I hope to get your help. Thank you

**Comment by ZcsrenlongZ** [comment]
Sorry for the late reply! We use these image ids for evaluation (see https://github.com/ZcsrenlongZ/ZoomGS/blob/main/ZoomGS/scene/dataset_readers.py#L167); and we perform ablation studies on 10 randomly selected scenes, ie, 01, 11, 13,  21, 23, 31, 61, 70, 84 ,88 and 90. Each scene is trained for 30000k iteration, the same as 3DGS. I hope this can help you.
